menu:
  class: sfPropelRouteCollection
  options:
    model:                Menu
    module:               menu
    prefix_path:          /menu
    column:               id
    with_wildcard_routes: true


flag_comment_delete_comment:
  url:   /flag_comment/:id/delete_comment
  param: { controller: flag_comment, action: delete_comment }

inappropriate_comment:
  class: sfPropelRouteCollection
  options:
    model:                InappropriateComment
    module:               flag_comment
    prefix_path:          /flag_comment
    column:               id
    with_wildcard_routes: true

inappropriate_flag_view:
  class: sfPropelRouteCollection
  options:
    model:                Inappropriate
    module:               flag_view
    prefix_path:          /flag_view
    column:               id
    with_wildcard_routes: true

partie:
  class: sfPropelRouteCollection
  options:
    model:                Partie
    module:               party
    prefix_path:          /party
    column:               id
    with_wildcard_routes: true

inappropriate:
  class: sfPropelRouteCollection
  options:
    model:                Inappropriate
    module:               flag
    prefix_path:          /flag
    column:               id
    with_wildcard_routes: true

badge:
  class: sfPropelRouteCollection
  options:
    model:                Badge
    module:               badge
    prefix_path:          /badge
    column:               id
    with_wildcard_routes: true

news:
  class: sfPropelRouteCollection
  options:
    model:                News
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

content:
  class: sfPropelRouteCollection
  options:
    model:                Content
    module:               mg_content_admin
    prefix_path:          /mg_content_admin
    column:               id
    with_wildcard_routes: true

page:
  class: sfPropelRouteCollection
  options:
    model:                Page
    module:               mg_page_admin
    prefix_path:          /mg_page_admin
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# default rules
homepage:
  url:   /
  param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
