<?php


/**
 * This class defines the structure of the 'post' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Feb 19 16:24:40 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.post.map
 */
class PostTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.post.map.PostTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('post');
		$this->setPhpName('Post');
		$this->setClassname('Post');
		$this->setPackage('lib.model.post');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('PARTIE_ID', 'PartieId', 'INTEGER', 'partie', 'ID', true, null, null);
		$this->addForeignKey('REPLICA_POST_ID', 'ReplicaPostId', 'INTEGER', 'post', 'ID', false, null, null);
		$this->addColumn('TYPE', 'Type', 'INTEGER', true, null, 1);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 255, null);
		$this->addColumn('URL', 'Url', 'VARCHAR', false, 255, null);
		$this->addColumn('TEXT', 'Text', 'LONGVARCHAR', false, null, null);
		$this->addColumn('PHOTO_FILE', 'PhotoFile', 'VARCHAR', false, 255, null);
		$this->addColumn('PHOTO_URL', 'PhotoUrl', 'VARCHAR', false, 255, null);
		$this->addColumn('QUOTE', 'Quote', 'LONGVARCHAR', false, null, null);
		$this->addColumn('QUOTE_AUTHOR', 'QuoteAuthor', 'VARCHAR', false, 255, null);
		$this->addColumn('LINK_TITLE', 'LinkTitle', 'VARCHAR', false, 255, null);
		$this->addColumn('LINK_URL', 'LinkUrl', 'VARCHAR', false, 255, null);
		$this->addColumn('LINK_IMAGE', 'LinkImage', 'VARCHAR', false, 255, null);
		$this->addColumn('VIDEO_URL', 'VideoUrl', 'VARCHAR', false, 255, null);
		$this->addColumn('TOTAL_INDEX', 'TotalIndex', 'FLOAT', true, null, 0);
		$this->addColumn('BEST_BADGE_1', 'BestBadge1', 'INTEGER', true, null, null);
		$this->addColumn('BEST_BADGE_2', 'BestBadge2', 'INTEGER', true, null, null);
		$this->addColumn('IS_PUBLISHED', 'IsPublished', 'BOOLEAN', true, null, true);
		$this->addColumn('IS_FEATURED', 'IsFeatured', 'BOOLEAN', true, null, false);
		$this->addColumn('COMMENTS_COUNT', 'CommentsCount', 'INTEGER', false, null, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Partie', 'Partie', RelationMap::MANY_TO_ONE, array('partie_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PostRelatedByReplicaPostId', 'Post', RelationMap::MANY_TO_ONE, array('replica_post_id' => 'id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('PostBadge', 'PostBadge', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Inappropriate', 'Inappropriate', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PostRelatedByReplicaPostId', 'Post', RelationMap::ONE_TO_MANY, array('id' => 'replica_post_id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('PostPollAnswer', 'PostPollAnswer', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PostPollVote', 'PostPollVote', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PostVisits', 'PostVisits', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PostDailyStats', 'PostDailyStats', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PostIndex', 'PostIndex', RelationMap::ONE_TO_MANY, array('id' => 'post_id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // PostTableMap
