generator:
  class: sfPropelGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              News
    plural:                Newss
    route_prefix:          news
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: News
        display: [=title, is_published, updated_at]
      
      filter:  ~
      form:
        display: 
          "General": [title, text, is_published]
      
      edit:
        title: Edit news %%title%%
      
      new:
        title: Create news
