all:
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp_host
          port:       465 #smtp_port
          encryption: ssl
          username:   smtp_username
          password:   smtp_password