<?php


/**
 * Skeleton subclass for representing a row from the 'badge_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/23/12 11:33:39
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.badge
 */
class BadgeType extends BaseBadgeType {

  public function __toString()
  {
    return $this->getName();
  }
} // BadgeType
