<?php


/**
 * This class defines the structure of the 'partie' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Feb 19 16:24:40 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.partie.map
 */
class PartieTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.partie.map.PartieTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('partie');
		$this->setPhpName('Partie');
		$this->setClassname('Partie');
		$this->setPackage('lib.model.partie');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 255, null);
		$this->addColumn('BIO', 'Bio', 'LONGVARCHAR', true, 1000, null);
		$this->addColumn('LOGO', 'Logo', 'VARCHAR', false, 255, null);
		$this->addColumn('URL', 'Url', 'VARCHAR', false, 255, null);
		$this->addColumn('FACEBOOK_PAGE', 'FacebookPage', 'LONGVARCHAR', false, null, null);
		$this->addColumn('TOTAL_INDEX', 'TotalIndex', 'FLOAT', true, null, 0);
		$this->addColumn('IS_PUBLISHED', 'IsPublished', 'BOOLEAN', true, null, true);
		$this->addColumn('COMMENTS_COUNT', 'CommentsCount', 'INTEGER', false, null, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfGuardUser', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Post', 'Post', RelationMap::ONE_TO_MANY, array('id' => 'partie_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PartieVisits', 'PartieVisits', RelationMap::ONE_TO_MANY, array('id' => 'partie_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PartieDailyStats', 'PartieDailyStats', RelationMap::ONE_TO_MANY, array('id' => 'partie_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PartieIndex', 'PartieIndex', RelationMap::ONE_TO_MANY, array('id' => 'partie_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('PartieCustomPoints', 'PartieCustomPoints', RelationMap::ONE_TO_MANY, array('id' => 'partie_id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // PartieTableMap
