<?php


/**
 * Skeleton subclass for performing query and update operations on the 'post_poll_vote' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/09/12 10:08:07
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.post
 */
class PostPollVotePeer extends BasePostPollVotePeer {

} // PostPollVotePeer
