<?php


/**
 * Skeleton subclass for representing a row from the 'partie_custom_points' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/04/12 10:35:00
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.rang
 */
class PartieCustomPoints extends BasePartieCustomPoints {

	/**
	 * Initializes internal state of PartieCustomPoints object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // PartieCustomPoints
