<?php


/**
 * Skeleton subclass for performing query and update operations on the 'partie_index' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/23/12 11:33:42
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.rang
 */
class PartieIndexPeer extends BasePartieIndexPeer {

} // PartieIndexPeer
