<?php


/**
 * Skeleton subclass for representing a row from the 'post_daily_stats' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/23/12 11:33:42
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.rang
 */
class PostDailyStats extends BasePostDailyStats {

	/**
	 * Initializes internal state of PostDailyStats object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
  
  public function calculateDailyIndex()
  {
    $index = 1 * $this->getComment() + 1 * $this->getBadge() + 0.1 * $this->getViews();
    $this->setCurrentIndex($index);
    $this->save();
  }

} // PostDailyStats
