<?php


/**
 * Skeleton subclass for performing query and update operations on the 'configuration' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Feb 19 16:24:39 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.configuration
 */
class ConfigurationPeer extends BaseConfigurationPeer {

  public static function set($name, $value){
    $c = new Criteria();
    $c->add(self::CODE, $name);
    $settings = self::doSelectOne($c);
    if(!empty($settings)){
      $settings->setValue($value);
      $settings->save();
      return $settings->getValue();
    }
    
    $settings = new Configuration();
    $settings->setCode($name);
    $settings->setValue($value);
    $settings->save();
    
    return $settings->getValue();
  }
  
  public static function get($name, $default = ''){
    $c = new Criteria();
    $c->add(self::CODE, $name);
    $value = self::doSelectOne($c);
    if(!empty($value)){
      return $value->getValue();
    }
    
    $value = new Configuration();
    $value->setCode($name);
    $value->setValue($default);
    $value->save();
    
    return $value->getValue();
  }
  
  public static function getLogoUrl(){
    $logo = ConfigurationPeer::get('logo');
    if($logo != ''){
      return sfConfig::get('logo_url') . '/' . $logo;
    }
  }
} // ConfigurationPeer
