<?php

/**
 * Skeleton subclass for performing query and update operations on the 'menu' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Feb 19 12:47:25 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.menu
 */
class MenuPeer extends BaseMenuPeer {

  public static function getMenuPath($Menu, $list = array()) {
    $list[] = $Menu;
    if ($Menu->getParentId() != NULL) {
      return self::getMenuPath(MenuPeer::retrieveByPK($Menu->getParentId()), $list);
    }
    return $list;
  }

  public static function getMenuTree($parent = NULL, $list = array(), $level = 0) {
    $level++;
    $c = new Criteria();
    $c->add(MenuPeer::PARENT_ID, $parent);
    $c->addAscendingOrderByColumn(MenuPeer::ORDER_POSITION);
    $objects = MenuPeer::doSelect($c);
    if (!empty($objects)) {
      foreach ($objects as $item) {
        $prefix = '';
        for ($i = 0; $i < ($level - 1) * 2; $i++) {
          $prefix .= '-';
        }
        $list[$item->getId()] = $prefix . $item->getTitle();
        $list = self::getMenuTree($item->getId(), $list, $level);
      }
    }
    return $list;
  }

  public static function getChildMenus($parent = null, $limit = 0) {
    $c = new Criteria();
    $c->add(MenuPeer::PARENT_ID, $parent);
    if ($limit != 0) {
      $c->setLimit($limit);
    }
    $c->addAscendingOrderByColumn(MenuPeer::ORDER_POSITION);
    $c->add(MenuPeer::IS_ENABLED, true);
    return MenuPeer::doSelect($c);
  }

}

// MenuPeer
