<?php


/**
 * Skeleton subclass for representing a row from the 'menu' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Feb 19 12:47:25 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.menu
 */
class Menu extends BaseMenu {

	/**
	 * Initializes internal state of Menu object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
  
  public function __toString(){
    return $this->getTitle();
  }
  
  public function getParsedLink(){
    return implGlobal::applyFilters($this->getLink());
  }

} // Menu
