<?php

/**
 * Skeleton subclass for performing query and update operations on the 'news' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/09/12 10:59:31
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.news
 */
class NewsPeer extends BaseNewsPeer {

  public static function getNewsList($limit = 0, $offset = 0) {
    $c = new Criteria();
    $c->add(NewsPeer::IS_PUBLISHED, true);
    $c->addDescendingOrderByColumn(NewsPeer::CREATED_AT);

    if ($limit > 0) {
      $c->setLimit($limit);
    }
    if ($offset > 0) {
      $c->setOffset($offset);
    }

    return NewsPeer::doSelect($c);
  }
  
  public static function retrieveByUrl($url)
  {
    $c = new Criteria();
    $c->add(self::URL, $url);
    return self::doSelectOne($c);
  }

}

// NewsPeer
