<?php


/**
 * Skeleton subclass for representing a row from the 'session' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/03/12 11:33:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.session
 */
class Session extends BaseSession {

} // Session
