<?php


/**
 * Skeleton subclass for representing a row from the 'inappropriate_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Feb  7 10:48:00 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.flag
 */
class InappropriateComment extends BaseInappropriateComment {

  public function getCount(){
    $c = new Criteria();
    $c->add(InappropriateCommentPeer::COMMENT_ID, $this->getCommentId());
    return InappropriateCommentPeer::doCount($c);
  }
  
} // InappropriateComment
