<?php


/**
 * Skeleton subclass for representing a row from the 'inappropriate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/23/12 11:33:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.flag
 */
class Inappropriate extends BaseInappropriate {

  public function getTypeText()
  {
    return __('Inappropriate');
  }
  
  public function getFlagCount()
  {
    $c = new Criteria();
    $c->add(InappropriatePeer::POST_ID, $this->getPostID());
    return InappropriatePeer::doCount($c);
  }
  
} // Inappropriate
