<?php


/**
 * Skeleton subclass for representing a row from the 'comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Feb  7 10:48:56 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.comment
 */
class Comment extends BaseComment {

  public function __toString() {
    return $this->getText();
  }
  
  public function getCreatedBy(){
    if($this->getUserId() != null){
      return $this->getsfGuardUser();
    }else{
      return $this->getName();
    }
  }
  
  public function canFlag(){
    $user = sfContext::getInstance()->getUser();
    if($user->isAuthenticated()){
      $c = new Criteria();
      $c->add(InappropriateCommentPeer::USER_ID, $user->getGuardUser()->getId());
      $c->add(InappropriateCommentPeer::COMMENT_ID, $this->getId());
      if(InappropriateCommentPeer::doCount($c) > 0){
        return false;
      }else{
        return true;
      }
    }
    return false;
  }
  
  public function canDelete(){
    $user = sfContext::getInstance()->getUser();
    if($user->isAuthenticated()){
      if($this->getUserId() == $user->getGuardUser()->getId()){
        return true;
      }
      
      if($user->hasCredential(array('Entire Admin', 'See Flag', 'Manage Flag'))){
        return true;
      }
    }
    return false;
  }
  
  public function getItemUrl(){
    if($this->getItemType() == 1){
      return PostPeer::retrieveByPK($this->getItemId())->getUrl();
    }else{
      return PartiePeer::retrieveByPK($this->getItemId())->getUrl();
    }
  }
  
} // Comment
