<?php


/**
 * Skeleton subclass for representing a row from the 'post_poll_answer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/09/12 10:08:07
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.post
 */
class PostPollAnswer extends BasePostPollAnswer {

  public function getVoteCount()
  {
    $c = new Criteria();
    $c->add(PostPollVotePeer::ANSWER_ID, $this->getId());
    $votesList = PostPollVotePeer::doSelect($c);
    $count = 0;
    if(!empty($votesList)) {
      foreach($votesList as $vote) {
        $count++;
      }
    }
    return $count;
  }
  
  protected function getHighVoteAnswer($postId)
  {
    $high = null;
    $c = new Criteria();
    $c->add(PostPollAnswerPeer::POST_ID, $postId);
    $list = PostPollAnswerPeer::doSelect($c);
    if(!empty($list)) {
      foreach($list as $val) {
        if($high == null) {
          $high = $val;
        } else if($val->getVoteCount() > $high->getVoteCount()) {
          $high = $val;
        }
      }
    }
    return $high;
  }
  
  public function getAnswerPercentOfBar()
  {
    //
    //return getAnswerPercentOfBar
    if($this->getHighVoteAnswer($this->getPostId()) != null && $this->getVoteCount() != 0 ) {
      return ($this->getVoteCount() / $this->getHighVoteAnswer($this->getPostId())->getVoteCount());
    }else{
      return 0.01;
    }
  }
  
} // PostPollAnswer
